import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { Montserrat } from "next/font/google";
import "./globals.css";
import ReactQueryProvider from "provider/reactQueryProvider";

const inter = Inter({ subsets: ["latin"] });
const montserrat = Montserrat({ subsets: ["latin"] })

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
   
      <html lang="en">
        
        <body className={`${montserrat.className} antialiased`}>
        <ReactQueryProvider>
          {children}
          </ReactQueryProvider>
          </body>
      </html>
   
    
  );
}
